### ISSUE TITLE
Create a Product Card for Our E-commerce Website

### ISSUE THREAD

**Issue by abc00xyz** [abc00xyz/Hacktoberfest--23#6]
## Description:
We're looking for a product card design for our e-commerce website. Your task is to design a product card that displays product details, images, prices, and a "Buy Now" button. Keep it simple and attractive.

* Difficulty: beginner
* Estimated Time: 3-4 hours

**Comment by DivyaSis** [comment]
**Hi User,**

Hi there! I'm interested in working on this issue. Could you please assign it to me? I believe I can make a valuable contribution to this task.

Looking forward to your response. Thanks!

**Comment by abc00xyz** [comment]
### Hello Divya,
Thank you for your interest in working on this issue. I've assigned the issue to you, and you can now start working on it. If you have any questions or need any assistance, feel free to ask. Good luck with your contribution!

Best regards,
[User](https://github.com/abc00xyz)
